### ISSUE TITLE
Cant Have 2 Carousals in same page

### ISSUE THREAD

**Issue by eXtizi** [YoussefRaafatNasry/portfolYOU#114]
the controls for the later one doesnt work. when click on them upper one changes

**Comment by seul1230** [comment]
Same here. Did you fix this problem?

**Comment by eXtizi** [comment]
No i did not. i just moved it to a different page. and if i have to take a guess i wud say it's because of same id or same class or something

**Comment by seul1230** [comment]
Oh, I fixed this with carousel id. Here's the link.

https://github.com/YoussefRaafatNasry/portfolYOU/pull/128#issue-2351800796

**Comment by eXtizi** [comment]
aha nice. terrific work.
Thank You.
Lemme close this issue.
