### ISSUE TITLE
Routing problem

### ISSUE THREAD

**Issue by enesusta** [YoussefRaafatNasry/portfolYOU#14]
Your work is awesome! I like it. But there is one problem. It works on local properly. But when I wants to publish on github pages, i cant access resources via navbar links.

For example:
enesusta.github.io/articles perfectly work.
![Screenshot_2](https://user-images.githubusercontent.com/32740550/70854359-86fad000-1ecb-11ea-957b-293f5c428c4d.png)

But I click the articles link on the navbar. It routes to me /articles/%20, therefore it doesnt exist any resources /articles/%20 , then 404.html not found triggered. 

![Screenshot_1](https://user-images.githubusercontent.com/32740550/70854355-78141d80-1ecb-11ea-8f7a-fad6093fb06f.png)

How can I fix this?
Regards.

**Comment by YoussefRaafatNasry** [comment]
Hey @enesusta ,
I will look into this and get back to you ASAP.

**Comment by YoussefRaafatNasry** [comment]
The problem seems to be caused by the plugin `jemoji`, I reported back to GitHub Pages and waiting for their response.

Here's a workaround if you don't care about emojis' support, just remove the following lines from your `_config.yaml`:

```yaml
plugins:
  - jemoji
```

**Comment by enesusta** [comment]
Thank you, my problem was solved. Thank you for your interest. It works properly 👍

**Comment by daco-tech** [comment]
As an alternative, you can add emojis using HTML and it does not require any faulty plugin. 
Example, add: 

> &#129488

To see the monocle emoji.

More details: https://emojiguide.org/face-with-monocle
