### ISSUE TITLE
images don't render properly

### ISSUE THREAD

**Issue by kerolloz** [YoussefRaafatNasry/portfolYOU#17]

**Comment by YoussefRaafatNasry** [comment]
Any more details?
Everything seems to be working properly.

**Comment by kerolloz** [comment]
https://youssefraafatnasry.me/portfolYOU/elements/#carousel

![image](https://user-images.githubusercontent.com/36763164/72666519-c1e8aa00-3a1b-11ea-8a49-ebcc34a6ba49.png)

**Comment by YoussefRaafatNasry** [comment]
They're working properly here.
I tried on both **Chrome** and **Edge** just to make sure.
_Please try different browsers and close the issue if it all goes fine._

![portfolYOU-elements](https://user-images.githubusercontent.com/41103290/72666657-3c65f980-3a1d-11ea-9783-1d06a0718a12.png)

**Comment by kerolloz** [comment]
surprisingly it doesn't work on Firefox.

**Comment by kerolloz** [comment]
tried a private window and it worked on Firefox
