### ISSUE TITLE
floating `<div class="list-group my-3">` tag

### ISSUE THREAD

**Issue by kerolloz** [YoussefRaafatNasry/portfolYOU#18]
would you please take a look at 
![image](https://user-images.githubusercontent.com/36763164/73392418-74552280-42e2-11ea-99ab-ff1ecd9d3b7e.png)

https://scu-icpc-community.github.io/blog/midyear-camp-contest2

https://github.com/SCU-ICPC-Community/SCU-ICPC-Community.github.io/blob/master/_posts/2020-01-28-midyear-camp-contest2.md

**Comment by YoussefRaafatNasry** [comment]
Try removing the hyphen from your `capture` tags.
_(i.e use `{% ... %}` instead of `{%- ... -%}`)_

**Comment by kerolloz** [comment]
@YoussefRaafatNasry Thank you that fixes the problem
