### ISSUE TITLE
Fail to build it

### ISSUE THREAD

**Issue by hongyi-huang** [YoussefRaafatNasry/portfolYOU#20]
I follow your instructions to install it. But it reports failure when building up. The message is enclosed here. As current instructions state, _includes folder should be deleted. But I wonder whether I should keep it as it was?

> The page build failed for the `master` branch with the following error:
> A file was included in `_projects/(2)` that is a symlink or does not exist in your `_includes` directory. For more information, see https://help.github.com/en/github/working-with-github-pages/troubleshooting-jekyll-build-errors-for-github-pages-sites#file-is-a-symlink.

**Comment by YoussefRaafatNasry** [comment]
You need to replace the [remote theme's line](https://github.com/hongyi-huang/hongyi-huang.github.io/blob/f39f8f9898e3bcdf0b77c76d47f5736455eda987/_config.yml#L9) in your _config.yml with this:

```yml
remote_theme        : YoussefRaafatNasry/portfolYOU
```

This will include theme's files _(as `_includes/**`, `_sass/**` and `_layouts/**`)_ remotely.
