### ISSUE TITLE
why two empty projects exist?

### ISSUE THREAD

**Issue by hongyi-huang** [YoussefRaafatNasry/portfolYOU#22]
Could you turn to https://hongyi-huang.github.io/projects/ to figure out why there are two placeholder-like empty projects? How could I move them away?

**Comment by YoussefRaafatNasry** [comment]
Projects prefixed with the GitHub logo are considered remote projects (_fetched from your GitHub repositories_), to configure (add/delete) them, modify the `remote-projects` filed in `pages/projects.html`'s front matter.
