### ISSUE TITLE
Disqus implementation

### ISSUE THREAD

**Issue by ranrinc** [YoussefRaafatNasry/portfolYOU#24]
Is there away to add disqus into our post or article? If yes how?

**Comment by YoussefRaafatNasry** [comment]
Unfortunately, it's not currently supported.
I will try to work on it in the next summer updates.
PRs are welcomed too, if you want to implement it yourself.

**Comment by ranrinc** [comment]
Hi @YoussefRaafatNasry,

I found a simple way of adding disqus to your template. It simply registered yourself to disqus and add disqus to your site.. Choose Universal Code and in my case, I choose the 1st options. Then add the code to _layouts/post.html put in on top of the footer. That's it. You should have disqus up and running.

**Comment by YoussefRaafatNasry** [comment]
I will try integrating it soon.

**Comment by rribeiro1** [comment]
I've just opened the PR https://github.com/YoussefRaafatNasry/portfolYOU/pull/28 to implement this. I am not a front-end developer but I tried to follow the pattern of the project.

**Comment by YoussefRaafatNasry** [comment]
@rribeiro1 Thanks a million for your contribution, I will review it soon.
