### ISSUE TITLE
How to have github logo on nav bar?

### ISSUE THREAD

**Issue by ranrinc** [YoussefRaafatNasry/portfolYOU#26]
Previously I can have github logo on my navbar. Now its gone. How can I bring it back?

<img width="313" alt="Screen Shot 2020-03-04 at 8 54 25 AM" src="https://user-images.githubusercontent.com/15801696/75836904-e34bfc80-5df5-11ea-8131-9f557a4f0a18.png">

**Comment by ranrinc** [comment]
nevermind.. I find out where its located...

**Comment by liver121888** [comment]
Mind if I ask... how can I bring it back?

**Comment by liver121888** [comment]
For anyone with this question:
add the following in navbar.html, just before the span tag
```  
<a class="nav-item nav-link " href="https://github.com/liver121888/liver121888.github.io">
    <i class="fab fa-1x fa-github">
    </i>
</a>
```
