### ISSUE TITLE
Stuck at jekyll serve

### ISSUE THREAD

**Issue by sudoeman89** [YoussefRaafatNasry/portfolYOU#32]
When doing jekyll serve I get:

C:/tools/ruby27/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/resolver.rb:290:in `block in verify_gemfile_dependencies_are_found!': Could not find gem 'github-pages x64-mingw32' in any of the gem sources listed in your Gemfile. (Bundler::GemNotFound)

How can I solve this?

Thanks in advance.

**Comment by YoussefRaafatNasry** [comment]
Just run that command before serving the website

```
bundle install
```

**Comment by YoussefRaafatNasry** [comment]
You get more help [here](https://help.github.com/en/github/working-with-github-pages/testing-your-github-pages-site-locally-with-jekyll).
