### ISSUE TITLE
Cannot change favicon and html

### ISSUE THREAD

**Issue by jingyi-xie** [YoussefRaafatNasry/portfolYOU#35]
I want to change the favicon and html files. I follow the doc by overriding the files. However, when I run "bundle exec jekyll serve", all the changes are gone and back to default. How should I fix it?

**Comment by jingyi-xie** [comment]
And when I publish it to GitHub pages, I have the same problem.

**Comment by jingyi-xie** [comment]
I solved the html problem by creating the "_layouts" folder. However, I still cannot change the favicon.

**Comment by dhecloud** [comment]
sorry but how did you solve it? u linked it to outside _site/assets?
