### ISSUE TITLE
Drop down menu

### ISSUE THREAD

**Issue by ranrinc** [YoussefRaafatNasry/portfolYOU#39]
Would like to make a dropdown menu if this possible? If not maybe a possible enhancement?

**Comment by YoussefRaafatNasry** [comment]
Since portfolYOU is based on Bootstrap,
You can use [Bootstrap's dropdown](https://getbootstrap.com/docs/4.4/components/navbar/#supported-content).

![image](https://user-images.githubusercontent.com/41103290/80440944-1bf5e700-890a-11ea-8d88-e1e40f155fa4.png)

**Comment by ranrinc** [comment]
alright.. will have to try.. thanks..
