### ISSUE TITLE
Allow small image size on project page?

### ISSUE THREAD

**Issue by renyuneyun** [YoussefRaafatNasry/portfolYOU#4]
Hi there,
Thank you for creating this theme. It's elegant and I'm using it for my portfolio page (yet my blog is in pelican :zipper_mouth_face:  ).

I'm wondering would you be willing to allow smaller cover images for each project (on the project page, of course)?
Currently, if I put a small image there, it will be resized to match the width (I suppose?). But I'm thinking of using different-sized images to represent different emphases of projects.

I see the reason of resizing: making them more uniformed, especially for larger pictures. And I'm aware there is a potential problem if the images are kept of their original sizes for responsive design.
But maybe allowing manual overridden of ratio may solve the problem? Say, by default 100%, but the user could manually override to, say, 40% and (the width of) that project card is resized.

**Comment by YoussefRaafatNasry** [comment]
Thanks @renyuneyun, Will surely do this soon!

**Comment by YoussefRaafatNasry** [comment]
If you mean the **card cover image**, I am afraid that I cannot fix this.
But the good new is that you can still resize your image using any photo editor software like Adobe Photoshop for example.

![card-header](https://user-images.githubusercontent.com/41103290/59551381-f6255500-8f78-11e9-834d-94b8e87a52d0.jpg)

**Comment by renyuneyun** [comment]
I was thinking about resizing too, but test shows me that this doesn't work. The image will be stretched to the full width (tested it again today)...
