### ISSUE TITLE
Add Disqus comment in blog section  

### ISSUE THREAD

**Issue by robustTechie** [YoussefRaafatNasry/portfolYOU#45]
Right now the blog doesn't provide in comment section, Disqus can provide this feature to add a comment section in the blog.

**Comment by rribeiro1** [comment]
Hi @robustTechie, it has support to disqus. 

Add this in your `_config.yml`:

``` yaml
disqus: your-Disqus-id
```

I am using in my page: https://rafaelribeiro.io/blog/amazon-budgets-slack-integration

**Comment by YoussefRaafatNasry** [comment]
Thanks to @rribeiro1, Disqus integration was added to portfolYOU in #28.
It's currently not documented but it will be before the next release, and after merging #48 as it adds some improvements to the existing implementation.

**Comment by rribeiro1** [comment]
Thank you @YoussefRaafatNasry 

Yes, I didn't touch on the documentation, I appreciate if you can help with that 👍
