### ISSUE TITLE
Pagination Support

### ISSUE THREAD

**Issue by erikyuzwa** [YoussefRaafatNasry/portfolYOU#53]
I've had to drop the use of this theme because I want to self-host it and not put it up on Github, but I REALLY LIKE IT 😿 . At any rate, I experimented with the `jekyll-paginate-v2` gem to add pagination support to the blog. It's not "perfect" but it sorta worked for me.

- Follow the gems documentation to update your `config.yml` (I could almost use all default settings)
- Rename the `pages/blog.md` to `pages/blog.html` and updated the markup to use this:

```
---
layout: default
title: Blog
weight: 2
permalink: /blog/
pagination: 
  enabled: true

---

{% include blog/search.html %}

<div class="card-group mt-2">

	{% for post in paginator.posts %}
	  {% include blog/post-card.html %}
	{% endfor %}
	
  </div>

{% if paginator.total_pages > 1 %}

<section class="pagination">

	{% if paginator.previous_page %}
	<div class="pagination__prev">
		<a href="{{ paginator.previous_page_path | relative_url }}" class="button button--large"><i class="fa fa-angle-left" aria-hidden="true"></i> <span>Newer Posts</span></a>
	</div>
	{% endif %}
	{% if paginator.next_page %}
	<div class="pagination__next">
		<a href="{{ paginator.next_page_path | relative_url }}" class="button button--large"><span>Older Posts</span> <i class="fa fa-angle-right" aria-hidden="true"></i></a>
	</div>
	{% endif %}

</section>

{% endif %}
```
Hope this helps anyone out there.

**Comment by YoussefRaafatNasry** [comment]
Thanks so much @erikyuzwa for sharing this.
I just want to mention that pagination support was dropped from this theme in f816530e74270eed6cd557453e7735b14a5c7b26 for testing purposes.
