### ISSUE TITLE
Skill Percentage Overlaps Title

### ISSUE THREAD

**Issue by saketrule** [YoussefRaafatNasry/portfolYOU#58]
In the skills progress bar, the percentage number overlaps with the title text if the number is low. 

![Screenshot 2020-10-31 at 12 52 01 AM](https://user-images.githubusercontent.com/22350546/97748329-4f146f80-1b13-11eb-92d5-ccaa719b5bdb.png)

Can we put in a fix for this? One way would be to have the percentage populated below instead of above the bar. 

For a temporary fix, I would like to play with the scss for
```
.skill-bar{...
```
Is there a proper way I can overwrite the default scss? I tried to add it to assets/styles.scss but it did not work.

Edit: I'm adding `<br> <br>` to the end of the name field. It provides a nice spacing between the title & the progress bar.

Thanks!

@rribeiro1

**Comment by BornToBeRoot** [comment]
@saketrule I have the same issue. Where can i add `<br> <br>` ? Can you post the file/line here?

**Comment by saketrule** [comment]
Hi @BornToBeRoot . In .yml file in `_data`, Add tasks like this, 
```
-  name: Get Standard ETA metrics <br> <br>                                                                                                                                                                      
   percentage: 30
   color:
```
