### ISSUE TITLE
Possible error in the installation guide

### ISSUE THREAD

**Issue by fakabbir** [YoussefRaafatNasry/portfolYOU#60]
Hi,

Thanks for the theme, it's among some of the simplest time for portfolio. 
While installation I notices that _includes, _layouts etc are required along with the _data folder

**But in the installation readme it says that the website would work without them too**... 

>**I wasn't able to get the theme working well without the _include and _layout folder.**

Can you please confirm if its the issue with instruction ?
https://youssefraafatnasry.me/portfolYOU/docs/

![image](https://user-images.githubusercontent.com/13721550/98560715-12443780-22ce-11eb-8611-b4532a07a89d.png)

**Comment by ChiBei** [comment]
same here

**Comment by YoussefRaafatNasry** [comment]
As per the docs:

> The following steps demonstrate how to use portfolYOU as **GitHub Pages remote theme**.

The theme's files _(like `_includes`, `_layouts`, etc.)_ are [included remotely](https://github.com/YoussefRaafatNasry/portfolYOU/blob/9c3f1aa3b583dc0d0b94965f4af4348f452fcf30/docs/_config.yml#L9) using the [remote-theme](https://github.com/benbalter/jekyll-remote-theme) plugin. This works well if you are hosting your site on GitHub Pages, not sure if it works on other hosting services by default.

If you aren't using GitHub Pages, you can still use the theme as a **fork** _(fork it and edit the files based on your needs)_ or as a [**gem-based theme**](https://learn.siteleaf.com/themes/gem-based-themes/) using this [gem](https://rubygems.org/gems/portfolyou-jekyll-theme).

**Comment by YoussefRaafatNasry** [comment]
Please reopen if this doesn't solve your issue.

**Comment by fakabbir** [comment]
> As per the docs:
> 
> > The following steps demonstrate how to use portfolYOU as **GitHub Pages remote theme**.
> 
> The theme's files _(like `_includes`, `_layouts`, etc.)_ are [included remotely](https://github.com/YoussefRaafatNasry/portfolYOU/blob/9c3f1aa3b583dc0d0b94965f4af4348f452fcf30/docs/_config.yml#L9) using the [remote-theme](https://github.com/benbalter/jekyll-remote-theme) plugin. This works well if you are hosting your site on GitHub Pages, not sure if it works on other hosting services by default.
> 
> If you aren't using GitHub Pages, you can still use the theme as a **fork** _(fork it and edit the files based on your needs)_ or as a [**gem-based theme**](https://learn.siteleaf.com/themes/gem-based-themes/) using this [gem](https://rubygems.org/gems/portfolyou-jekyll-theme).

using github page..... the project structure is https://github.com/fakabbir/fakabbir.github.io

**Comment by YoussefRaafatNasry** [comment]
Change `remote_theme` in [`_config.yml`](https://github.com/fakabbir/fakabbir.github.io/blob/d47a5b6c10fcc4d0f7e6ddafadc5d3b09505f1dd/_config.yml#L9) back to `YoussefRaafatNasry/portfolYOU`, because this is where the theme's files are hosted, then delete the theme files as mentioned in the docs, yo won't need them: https://github.com/YoussefRaafatNasry/portfolYOU/blob/3ffc7bb278b7d182e13a7bd12f51562b88946b85/docs/_config.yml#L9
