### ISSUE TITLE
Support for Latex

### ISSUE THREAD

**Issue by sharmaabhishekk** [YoussefRaafatNasry/portfolYOU#65]
Hi 👋 and thank you for this excellent theme. I've been using it for more than a year now and I am loving it. 

Some of my recent work needs **_latex formatting_**. I was wondering if portfolYOU has support for that and if not, is there a way to work around somehow so that I can  use latex inside markdown.

Thanks!

**Comment by sharmaabhishekk** [comment]
Never mind, I figured it out with some good old Stackoverflow help. Here are the steps in case anyone wants to know:

* Make sure the `_includes` folder exists in your local repository of `<your-username>.github.io`
* Add the following code block to the `head.html` file in `_includes` anywhere in the `<head>` block: 
```
<script type="text/x-mathjax-config">
    MathJax.Hub.Config({
      tex2jax: {
        skipTags: ['script', 'noscript', 'style', 'textarea', 'pre'],
        inlineMath: [['$','$']]
      }
    });
  </script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/latest.js?config=TeX-MML-AM_CHTML" type="text/javascript"></script> 
```
* Try an example latex string (example: $h_\theta(x) = \Large\frac{1}{1 + \mathcal{e}^{(-\theta^\top x)}}$)

This worked for me.

**Comment by navaneethnpk** [comment]
I tried this in my website. It did not work on mine.
There was no "head.html" in my "_includes", so i created on and added the code.
