### ISSUE TITLE
How to Rename Navigation Links?

### ISSUE THREAD

**Issue by sipedia** [YoussefRaafatNasry/portfolYOU#66]

**Comment by YoussefRaafatNasry** [comment]
Can you please provide more details, like which text in the navbar?

**Comment by sipedia** [comment]
how to rename the navbar name like tags,project,blog about,sorry for my bad english

**Comment by YoussefRaafatNasry** [comment]
You can edit the [title](https://github.com/YoussefRaafatNasry/portfolYOU/blob/b29ec7c2f045e02c54e7f52b253fc5f6d6591b73/docs/pages/blog.html#L3) in the pages [front matter](https://jekyllrb.com/docs/front-matter/) to match your needs.
