### ISSUE TITLE
Change an element of the theme!

### ISSUE THREAD

**Issue by geekyJock8** [YoussefRaafatNasry/portfolYOU#7]
First of all, I absolutely love your theme. The best one I've seen.

I was wondering if how can I change elements of the theme.
Specifically, I wanted to **remove the percentage**(line bar) in Skills(Programming and others) and **replace it with a small description**. 

![image](https://user-images.githubusercontent.com/19239291/62267413-a4ae2800-b449-11e9-9a83-2d98b0ab7c47.png)

**Comment by YoussefRaafatNasry** [comment]
Thanks @geekyJock8 for your admiration!

To achieve this you will need to edit the [`skills.html`](https://github.com/YoussefRaafatNasry/portfolYOU/blob/master/_includes/about/skills.html) file and `div` containing the span with a `p` or any element to hold your text. Also replace the word `percentage` with `description` in both [`skills.html`](https://github.com/YoussefRaafatNasry/portfolYOU/blob/master/_includes/about/skills.html) and [`_data/*-skills.yml`](https://github.com/YoussefRaafatNasry/portfolYOU/blob/master/_data) to be more meaningful.
