### ISSUE TITLE
Removing 👋 Breaks About Page

### ISSUE THREAD

**Issue by BornToBeRoot** [YoussefRaafatNasry/portfolYOU#70]
Hi @YoussefRaafatNasry,

the new dark / light design looks awesome 👍 Great work!

After i update / deployed a new github page, the about page is broken (i already cleared the cache and tried from another device):

![image](https://user-images.githubusercontent.com/16019165/117503614-798f2b80-af81-11eb-95a8-c4895de32bb6.png)

Any idea? 

Here is the code https://github.com/BornToBeRoot/borntoberoot.github.io

Greetings

**Comment by YoussefRaafatNasry** [comment]
This is an interesting bug, seems like removing the `:wave:` 👋 emoji breaks the page, I don't know the reason behind this yet. I will push a fix as soon as I find the reason.


|                                                   With :wave:                                                   |                                             Without :wave: (bugged)                                             |
|:---------------------------------------------------------------------------------------------------------------:|:---------------------------------------------------------------------------------------------------------------:|
| ![image](https://user-images.githubusercontent.com/41103290/117507828-e5749280-af87-11eb-86cf-c253408b62b3.png) | ![image](https://user-images.githubusercontent.com/41103290/117507579-8878dc80-af87-11eb-9dfd-7bd66c6c2e0b.png) |

**Comment by YoussefRaafatNasry** [comment]
@BornToBeRoot can you make sure this works, please?
Reopen if the issue still exists.

**Comment by BornToBeRoot** [comment]
@YoussefRaafatNasry works! Thank you :) 

interesting bug 🐛
