### ISSUE TITLE
Usage Issues

### ISSUE THREAD

**Issue by 0x44RU5H** [YoussefRaafatNasry/portfolYOU#72]
I have been attempting to implement this theme into by jekyll site, but the theme does not work. Please add usage steps to make this more straightforward.

**Comment by PhaelIshall** [comment]
@YoussefRaafatNasry I think they mean running it locally. It shows an error that it does not find 'jemoji'. Did you have to install anything?

**Comment by YoussefRaafatNasry** [comment]
> @YoussefRaafatNasry I think they mean running it locally. It shows an error that it does not find 'jemoji'. Did you have to install anything? 

Did you run `bundle install` as mentioned [here](https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/testing-your-github-pages-site-locally-with-jekyll#building-your-site-locally)?

**Comment by YoussefRaafatNasry** [comment]
Please reopen this if there's any updates.
