### ISSUE TITLE
Include Mastodon in social accounts list in footer (& suppor other federated networks)

### ISSUE THREAD

**Issue by keunes** [YoussefRaafatNasry/portfolYOU#75]
Hello!

I'm just getting started with Jekyll and am building my first site using this theme. It looks neat and clean :)

I wanted to add  a link to my mastodon profile in the footer. I have added the following to `_config.yml`:
```
  mastodon          : keunes
  mastodon_server   : mastodon.social # instance domain without protocol (e.g. mastodon.social)
```

I am recording the username and server separately, because the profile url is `https://mastodon_server/@mastodon`, while the user handle (which I might like to display somewhere, later on) is like `@mastodon@mastodon_server`

In `_data/social-media.yml` I've added mastodon, but I don't know how to reference a variable (?) from another yml file within it. I've tried the following and some other variations, but can't get it to work :)

```
mastodon:
  url   : https://{{site.author.mastodon_server}}/@
  icon  : fab fa-mastodon
  color : 3088d4
```

On [StackOverflow](https://stackoverflow.com/questions/2063616/how-to-reference-a-yaml-setting-from-elsewhere-in-the-same-yaml-file) I see that it might not at all be (easily) possible. Maybe if including a variable to form a new variable isn't possible, maybe support for federated media (actually also GitLab, which could be self-hosted) could be implemented by adjusting `_includes/social.html`?

If I had known how to make this work I would've sent a PR. But so this is more like a feature request to include support for Mastodon with deep support for the federated nature (splitting domain and username).

Thanks either way for providing this theme!

**Comment by YoussefRaafatNasry** [comment]
Hello @keunes!

As far as I know, you can't use jekyll variables in YAML files.

But why you don't want to use the URL of the sever as is? You can still keep them in `_config.yml` for usage other than the social links. Here's what I mean: 

```yaml
mastodon:
  url   : https://mastodon.social/@
  icon  : fab fa-mastodon
  color : 3088d4
```

**Comment by keunes** [comment]
Thanks for the quick reply! :)

> why you don't want to use the URL of the sever as is?

Sure that'd work for me, but it wouldn't be a federation-worthy implementation of social support for Mastodon. So I wouldn't send a PR with that approach :)
There's really a lot of servers (the 'main' one even closed nee registrations), and asking theme users to adjust something in the theme files that they have already provided in `_config.yml`

**Comment by YoussefRaafatNasry** [comment]
I understand now your point of view. But as I mentioned before, that wouldn't be possible in jekyll. So the only approach now is to add it to the social links manually and not through `_config.yaml`. We can add this later whenever it become supported by jekyll.
