### ISSUE TITLE
How to use my local image instead of always using the image from the network

### ISSUE THREAD

**Issue by NaagAlgates** [YoussefRaafatNasry/portfolYOU#86]
Hello Youssef,

Firstly thank you for your amazing work. Please let me know if this question is previously fixed.

As per the documentation, it is very clear that I can use the below syntax to display an image

`{% include elements/figure.html image="https://bit.ly/2N69TKO" caption="The Ocean" %}`

My Questions here is, 

Is it possible to use my local image (`/assests/img/post/my-post/1.jpg`) instead of `https://bit.ly/2N69TKO`

{% include elements/figure.html image="/assests/img/post/my-post/1.jpg" caption="The Ocean" %}

I tried to use the local image but this is the response

![image](https://user-images.githubusercontent.com/14884575/134304467-c647f883-6f80-417e-b2a6-71aeac6e3309.png)

**Comment by YoussefRaafatNasry** [comment]
Sorry it took too long, this is now fixed!

**Comment by NaagAlgates** [comment]
Thank you
