### ISSUE TITLE
Respect GitHub ProjectName case

### ISSUE THREAD

**Issue by Rjvs** [YoussefRaafatNasry/portfolYOU#91]
Hi, when using the `remote_projects` feature, the resulting project cards don't respect the case of the project name.  Instead, it appears to convert them to lowercase and then capitalise the first letter.  While it is common for project names to use all lowercase, protfolYOU doesn't follow that convention (and nor do many of our repos).  

It would be preferable if the case of the project name was not changed -- and I expect that even for lowercase project names this would still work well.

**Comment by Rjvs** [comment]
Easily fixed in a fork but not easy to see how to get the best of both worlds.

**Comment by YoussefRaafatNasry** [comment]
Maybe we can add an option to add display names for each repository.
PRs are welcomed if you want to work on this feature.
